-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg0bEx4s3OoQyQjB9P
nSkloyIaoEDh8jrMvHIA939NjmGgCgYIKoZIzj0DAQehRANCAAQYNOCCezJCmNSn
ZOZBGrb5u1aV2jNSPMBZaPPJ7S2vONOe8/brlR6yUrqiJq4LRMZ2zQsaurUObAtF
k5Ma/G5T
-----END PRIVATE KEY-----